version: '2'
services:
  ecommerce-fashion:
    build:
      context: .
      dockerfile: Dockerfile
    image: image-service
    env_file:
      - .env
    ports:
      - "9099:9099"

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    container_name: image-service
    volumes:
      - /opt/global:/opt/global/
    mem_limit: 1G
    restart: always
    networks:
      - longnh

networks:
  longnh:
    driver: bridge